apiVersion: v1
kind: Secret
metadata:
  name: htpasswd-secret
  namespace: openshift-config
type: Opaque
stringData:
  htpasswd: |
    dXNlcjE6JDJ5JDA1JDBmVVR0ODFYNlQzZFBaOTdPMUFHQy5MaC9NSTE4UjNkQk9qLjZwUDhFOU05
    MUlENGhHcTNhCg==
